# This workflow will build a golang project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-go

name: Go

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: 'stable'

    - name: Build
      run: go build -v ./...

    - name: Test
      run: go test -v ./...

    - name: Run Test Coverage
      run: go test -coverprofile=coverage.txt

    - name: Upload coverage to Codecov
      run: bash <(curl -s https://codecov.io/bash)

  docker:
    runs-on: ubuntu-latest
    needs: build
    steps:
    - uses: actions/checkout@v4

    - name: Build Docker image
      run: docker build -t autowordle .

    - name: Run tests in Docker
      run: docker run --rm autowordle go test -v ./...
